package sgr

const (
	ResetName = "reset"

	BoldName                 = "bold"
	FaintName                = "faint"
	ItalicName               = "italic"
	FrakturName              = "fraktur"
	ReversedName             = "reversed"
	NormalIntensityName      = "normal-intensity"
	NotItalicBlackLetterName = "not-italic-black-letter"
	NotReversedName          = "not-reversed"

	UnderlineName        = "underline"
	DoublyUnderlinedName = "doubly-underlined"
	SlowBlinkName        = "slow-blink"
	RapidBlinkName       = "rapid-blink"
	OverlinedName        = "overlined"
	NotUnderlinedName    = "not-underlined"
	NotBlinkingName      = "not-blinking"
	NotOverlinedName     = "not-overlined"

	ConcealName                    = "conceal"
	CrossedOutName                 = "crossed-out"
	DisableProportionalSpacingName = "disable-proportional-spacing"
	RevealName                     = "reveal"
	NotCrossedOutName              = "not-crossed-out"
	ProportionalSpacingName        = "proportional-spacing"

	FramedName                  = "framed"
	EncircledName               = "encircled"
	SuperscriptName             = "superscript"
	SubscriptName               = "subscript"
	NotFramedEncircledName      = "not-framed-encircled"
	NotSuperscriptSubscriptName = "not-superscript-subscript"

	IdeogramUnderlineName       = "ideogram-underline"
	IdeogramDoubleUnderlineName = "ideogram-double-underline"
	IdeogramOverlineName        = "ideogram-overline"
	IdeogramDoubleOverlineName  = "ideogram-double-overline"
	IdeogramStressMarkingName   = "ideogram-stress-marking"
	NoIdeogramAttributesName    = "no-ideogram-attributes"

	FgBlackName   = "fg-black"
	FgRedName     = "fg-red"
	FgGreenName   = "fg-green"
	FgYellowName  = "fg-yellow"
	FgBlueName    = "fg-blue"
	FgMagentaName = "fg-magenta"
	FgCyanName    = "fg-cyan"
	FgWhiteName   = "fg-white"

	BgBlackName   = "bg-black"
	BgRedName     = "bg-red"
	BgGreenName   = "bg-green"
	BgYellowName  = "bg-yellow"
	BgBlueName    = "bg-blue"
	BgMagentaName = "bg-magenta"
	BgCyanName    = "bg-cyan"
	BgWhiteName   = "bg-white"

	FgBrightBlackName   = "fg-bright-black"
	FgBrightRedName     = "fg-bright-red"
	FgBrightGreenName   = "fg-bright-green"
	FgBrightYellowName  = "fg-bright-yellow"
	FgBrightBlueName    = "fg-bright-blue"
	FgBrightMagentaName = "fg-bright-magenta"
	FgBrightCyanName    = "fg-bright-cyan"
	FgBrightWhiteName   = "fg-bright-white"

	BgBrightBlackName   = "bg-bright-black"
	BgBrightRedName     = "bg-bright-red"
	BgBrightGreenName   = "bg-bright-green"
	BgBrightYellowName  = "bg-bright-yellow"
	BgBrightBlueName    = "bg-bright-blue"
	BgBrightMagentaName = "bg-bright-magenta"
	BgBrightCyanName    = "bg-bright-cyan"
	BgBrightWhiteName   = "bg-bright-white"

	CustomFgColorName         = "custom-fg-color"
	DefaultFgColorName        = "default-fg-color"
	CustomBgColorName         = "custom-bg-color"
	DefaultBgColorName        = "default-bg-color"
	CustomUnderlineColorName  = "custom-underline-color"
	DefaultUnderlineColorName = "default-underline-color"

	FgColor256Name        = "fg-color-256"
	FgColorRGBName        = "fg-color-rgb"
	BgColor256Name        = "bg-color-256"
	BgColorRGBName        = "bg-color-rgb"
	UnderlineColor256Name = "underline-color-256"
	UnderlineColorRGBName = "underline-color-rgb"

	PrimaryFontName      = "primary-font"
	AlternativeFont1Name = "alternative-font1"
	AlternativeFont2Name = "alternative-font2"
	AlternativeFont3Name = "alternative-font3"
	AlternativeFont4Name = "alternative-font4"
	AlternativeFont5Name = "alternative-font5"
	AlternativeFont6Name = "alternative-font6"
	AlternativeFont7Name = "alternative-font7"

	AlternativeFont8Name = "alternative-font8"
	AlternativeFont9Name = "alternative-font9"
)
